### ISSUE TITLE
Missing Extraction Code for Downloading Pretrained Model on Baidu Pan

### ISSUE THREAD

**Issue by Luo-Yihang** [shuchenweng/CT2#1]
Hi, When I was trying download the pretrained model on Baidu Pan, it requires me to provide the extraction code. Could you please also include the extraction in README?
Thank you!

**Comment by shuchenweng** [comment]
It is v4ay. Sorry for the trouble - -

**Comment by shuchenweng** [comment]
> Hi, When I was trying download the pretrained model on Baidu Pan, it requires me to provide the extraction code. Could you please also include the extraction in README? Thank you!


It is v4ay. Sorry for the trouble - -

**Comment by Luo-Yihang** [comment]
Thank you!
