### ISSUE TITLE
How could I address the two issues when I run test.py

### ISSUE THREAD

**Issue by tsz12** [shuchenweng/CT2#11]
FileNotFoundError: [Errno 2] No such file or directory: 'E:/samsung/datasets/imagenetval/val5000/val_fullfilenames.pickle'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6067)

**Comment by shuchenweng** [comment]
change the directory to correct val_fullfilenames.pickle path please
