### ISSUE TITLE
Could you provide the pretrained weights of vit_base_patch32_384 and vit_small_patch32_384? 

### ISSUE THREAD

**Issue by YJ-Pan** [shuchenweng/CT2#12]
The work looks well and I'd like to try it. But I can't run the code with the provided pretrained weights due to the memory constraint of my gpu. Could you please include the pretrained weights of vit_base_patch32_384 and vit_small_patch32_384? Thanks!

**Comment by shuchenweng** [comment]
https://github.com/BBuf/vit-profile/blob/7b7750c21849eefd1cbb2b47e8c8ed7d8604cf82/lib/vit.py.  This may help you.
