### ISSUE TITLE
Inference image on its original demension

### ISSUE THREAD

**Issue by Luo-Yihang** [shuchenweng/CT2#3]
When I ran the testing scripts with the pretrained models, I find I can only use 256\*256 input image (or resize/crop my input image to 256\*256). May I ask is there any chance for me to test any size image on its original demension?

**Comment by shuchenweng** [comment]
Sorry that we could only colorize 256*256 images.

**Comment by shuchenweng** [comment]
> When I ran the testing scripts with the pretrained models, I find I can only use 256*256 input image (or resize/crop my input image to 256*256). May I ask is there any chance for me to test any size image on its original demension?


Sorry that we could only colorize 256*256 images.

**Comment by yuchen202** [comment]
Where should the colored picture directory be placed in the test parameter

**Comment by Luo-Yihang** [comment]
can use "dataset_dir",  you can find it in [sgem/test.py](https://github.com/shuchenweng/CT2/blob/main/segm/test.py)
