### ISSUE TITLE
Missing declaration and description  ！

### ISSUE THREAD

**Issue by OHaiYo-lzy** [shuchenweng/CT2#4]
Missing declaration and description for "ptu" and "dist" in metrics.py. Hopefully it will be explained!

**Comment by shuchenweng** [comment]
I see. We will check carefully in a few days. We are a little busy these days.

**Comment by shuchenweng** [comment]
> Missing declaration and description for "ptu" and "dist" in metrics.py. Hopefully it will be explained!

I see. We will check carefully in a few days. We are a little busy these days.
