### ISSUE TITLE
Alternative link to the pretained weights, please?

### ISSUE THREAD

**Issue by gessyoo** [shuchenweng/CT2#5]
Your code looks very interesting and I'd like to test it locally.  But I can't connect to the link to download the pretrained weights.  Others who have tried to download the pretrained weights report that the link requires the user to download and install an unknown application, which raises security and privacy concerns.  Could you please include the pretrained weights on your github page or put the weights on a more user-friendly, easily accessible public site?

**Comment by shuchenweng** [comment]
We upload it to the Google Driver, https://drive.google.com/file/d/15LsqvHu1_g6OEEUbir7i1wbLDxIP4LTU/view?usp=sharing. Did that help you?
