### ISSUE TITLE
Could you provide mask_prior.pickle?

### ISSUE THREAD

**Issue by asdf1996** [shuchenweng/CT2#6]
Hi @shuchenweng :
Could you please provide **mask_prior.pickle**?
Now i want to test my own images for colorization but the **test.py** and **single_test.py** can't run successfully due to the lack of some pre-trained weights.
It will be better if you can provide one easy to run Colab demo for testing colorization.

**Comment by Catrin-baze** [comment]
There is a mask_prior.pickle [https://github.com/shuchenweng/CT2/blob/main/mask_prior.pickle](url) .I don't know if it can be used.I'm also testing pretrained model on colab,but the effect of colorized image is very different from that in the paper.Have you run your results yet?

**Comment by shuchenweng** [comment]
> Hi @shuchenweng : Could you please provide **mask_prior.pickle**? Now i want to test my own images for colorization but the **test.py** and **single_test.py** can't run successfully due to the lack of some pre-trained weights. It will be better if you can provide one easy to run Colab demo for testing colorization.

Yes, it could download here https://github.com/shuchenweng/CT2/blob/main/mask_prior.pickle.

**Comment by shuchenweng** [comment]
> There is a mask_prior.pickle [https://github.com/shuchenweng/CT2/blob/main/mask_prior.pickle](url) .I don't know if it can be used.I'm also testing pretrained model on colab,but the effect of colorized image is very different from that in the paper.Have you run your results yet?

We have updated the code and readme to avoid the confusion. This bug is caused by the incorrected pretrained weight name, which makes the model fail to load the weight.

**Comment by OHaiYo-lzy** [comment]
I also want to test on my own dataset or other dataset other than imagenet, how can I do that?
Anyway thanks for your gorgeous work!

**Comment by shuchenweng** [comment]
> I also want to test on my own dataset or other dataset other than imagenet, how can I do that? Anyway thanks for your gorgeous work!

Load our pretrained weight and modify the dataloader: https://github.com/shuchenweng/CT2/tree/main/segm/data.

BTW, the simplest approach is to reorganize data format in other dataset so that it has the same representation as Imagenet

**Comment by asdf1996** [comment]
> 

Hi @shuchenweng  
Could you explain more about how to test your model on other  images? Do i need to prepare one **mask_prior.pickle** for my own data? And how to generate this if it's necessary ？
Since this code is kind of complicated and has so many parameters , it will be great if you can provide one easy to run colab demo. Thanks a lot!

**Comment by asdf1996** [comment]
> There is a mask_prior.pickle [https://github.com/shuchenweng/CT2/blob/main/mask_prior.pickle](url) .I don't know if it can be used.I'm also testing pretrained model on colab,but the effect of colorized image is very different from that in the paper.Have you run your results yet?


@OHaiYo-lzy  I have not run test.py or single_test.py sucessfully  yet,  could you please share your colab demo of testing this model on real world images?

**Comment by shuchenweng** [comment]
> > 
> 
> Hi @shuchenweng Could you explain more about how to test your model on other images? Do i need to prepare one **mask_prior.pickle** for my own data? And how to generate this if it's necessary ？ Since this code is kind of complicated and has so many parameters , it will be great if you can provide one easy to run colab demo. Thanks a lot!

You dont need to prepare another mask_prior.pickle. Just use it. This file is build to acquire the mapping from L to candidate ab range, which supports LSM and Color query/attention module proposed in our paper. 

What is your suffered problem when running our model?

**Comment by shuchenweng** [comment]
> > There is a mask_prior.pickle [https://github.com/shuchenweng/CT2/blob/main/mask_prior.pickle](url) .I don't know if it can be used.I'm also testing pretrained model on colab,but the effect of colorized image is very different from that in the paper.Have you run your results yet?
> 
> @OHaiYo-lzy I have not run test.py or single_test.py sucessfully yet, could you please share your colab demo of testing this model on real world images?

We are doing it!
