### ISSUE TITLE
why the test result is very different from paper?

### ISSUE THREAD

**Issue by Catrin-baze** [shuchenweng/CT2#7]
I load the provided pretrained weight to test ,but the effect seems not very good.

**Comment by shuchenweng** [comment]
> I load the provided pretrained weight to test ,but the effect seems not very good.

Rename the pretrained weight after decompression as "checkpoint.pth" and move it to the log-dir (segm/vit-large). The weired results are caused by incorrectly weight loading. We have updated the code and readme to add assertation and detailed instructions.
