### ISSUE TITLE
Could you provide clean_train_filenames.pickle?

### ISSUE THREAD

**Issue by shunyuan970503** [shuchenweng/CT2#9]
Could you please provide the clean train data list in [segm/data/coco.py's L85](https://github.com/shuchenweng/CT2/blob/main/segm/data/coco.py#L85), since there may exist something different with the one generated on the whole training set of ImageNet.

**Comment by shuchenweng** [comment]
Sorry, [segm/data/coco.py](https://github.com/shuchenweng/CT2/blob/main/segm/data/coco.py#L85) is copied from another project and we never use it.

**Comment by shunyuan970503** [comment]
Thanks for your answering. But when run the training script, a .pickle file will be actually generated according to [segm/data/coco.py's L88-L100](https://github.com/rstrudel/segmenter/tree/master/segm/data) which covers all ImageNet training samples.

**Comment by shuchenweng** [comment]
> Thanks for your answering. But when run the training script, a .pickle file will be actually generated according to [segm/data/coco.py's L88-L100](https://github.com/shuchenweng/CT2/blob/main/segm/data/coco.py#L88-L100) which covers all ImageNet training samples.

Hi, sorry for the late reply, we provide the clean_train_filenames.pickle [here](https://github.com/shuchenweng/CT2/blob/main/clean_train_filenames.zip), where we filter out the grayscale images in ImageNet without RGB ground truth. Unzip it and use it please.

**Comment by shunyuan970503** [comment]
> > Thanks for your answering. But when run the training script, a .pickle file will be actually generated according to [segm/data/coco.py's L88-L100](https://github.com/shuchenweng/CT2/blob/main/segm/data/coco.py#L88-L100) which covers all ImageNet training samples.
> 
> Hi, sorry for the late reply, we provide the clean_train_filenames.pickle [here](https://github.com/shuchenweng/CT2/blob/main/clean_train_filenames.zip), where we filter out the grayscale images in ImageNet without RGB ground truth. Unzip it and use it please.

Thanks!
